name: ealmashi
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.2.2+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_bloc: ^7.2.0
  easy_localization: ^3.0.0
  shimmer: ^2.0.0
  json_serializable: ^4.1.4
  shared_preferences: ^2.0.7
  data_connection_checker_tv: ^0.3.5-nullsafety
  get_it: ^7.0.0
  dartz: ^0.10.0
  flutter_screenutil: ^5.0.0+2
  equatable: ^2.0.3
  url_launcher: ^6.0.9
  persistent_bottom_nav_bar: ^4.0.2
  flutter_svg: ^0.22.0
  awesome_dialog: ^2.1.1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  fluttertoast: ^8.0.8
  cached_network_image: ^3.1.0+1
  image_picker: ^0.8.4
  firebase_messaging: ^11.2.0
  firebase_core: ^1.10.1
  cloud_firestore: ^2.0.0
  google_maps_flutter: ^2.0.4
  location: ^4.3.0
  geolocator: ^8.0.1
  share_plus: ^4.0.4
  flutter_local_notifications:
  flutter_slidable: ^1.2.0
  file_picker: ^4.6.1
  open_file: ^3.2.1
  path_provider: ^2.0.5
#  firebase_storage: ^10.0.2
#  record_mp3: ^3.0.0
#  permission_handler: ^10.0.0
#  audioplayers: ^1.0.1
#  path: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  built_value_generator: ^8.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Nahdi
      fonts:
        - asset: assets/fonts/NahdiBold.ttf

    - family: Noto
      fonts:
        - asset: assets/fonts/NotoKufiArabic.ttf

    - family: Bukra
      fonts:
        - asset: assets/fonts/29LTBukra.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
